---
# tasks file for ansible-docker
- name: Add docker repository
  yum_repository:
    name: dockerrepo
    description: "Docker Repository"
    baseurl: "https://yum.dockerproject.org/repo/main/centos/7/"
    gpgkey: "https://yum.dockerproject.org/gpg"
    gpgcheck: yes

- name: Install docker
  yum:
    name: docker-engine
    state: present

- name: Start and enable docker service
  service:
    name: docker
    state: started
    enabled: yes
